#!/usr/local/bin/ruby
require "autotest"
require "autozest"

module Autotest::Growl  
  Autotest.add_hook :ran_command do |auto_test|
    # Hand off notification to AutoZest
    AutoZest::Notifier.notify!(auto_test.results)
  end
end
